[2023-05-07T15:53:26.013-0300] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bigdata_tp.TopCTR manual__2023-05-07T18:51:01.197398+00:00 [queued]>
[2023-05-07T15:53:26.022-0300] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bigdata_tp.TopCTR manual__2023-05-07T18:51:01.197398+00:00 [queued]>
[2023-05-07T15:53:26.022-0300] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-07T15:53:26.023-0300] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-07T15:53:26.023-0300] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-07T15:53:26.042-0300] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): TopCTR> on 2023-05-07 18:51:01.197398+00:00
[2023-05-07T15:53:26.106-0300] {standard_task_runner.py:55} INFO - Started process 2027 to run task
[2023-05-07T15:53:26.117-0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'bigdata_tp', 'TopCTR', 'manual__2023-05-07T18:51:01.197398+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpqznrti_6']
[2023-05-07T15:53:26.122-0300] {standard_task_runner.py:83} INFO - Job 60: Subtask TopCTR
[2023-05-07T15:53:26.203-0300] {task_command.py:389} INFO - Running <TaskInstance: bigdata_tp.TopCTR manual__2023-05-07T18:51:01.197398+00:00 [running]> on host DESKTOP-02TA80M.localdomain
[2023-05-07T15:53:26.273-0300] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=bigdata_tp
AIRFLOW_CTX_TASK_ID=TopCTR
AIRFLOW_CTX_EXECUTION_DATE=2023-05-07T18:51:01.197398+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-07T18:51:01.197398+00:00
[2023-05-07T15:53:26.275-0300] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alanmatys/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/alanmatys/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: TopCTR() missing 1 required positional argument: 'ads_views'
[2023-05-07T15:53:26.283-0300] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=bigdata_tp, task_id=TopCTR, execution_date=20230507T185101, start_date=20230507T185326, end_date=20230507T185326
[2023-05-07T15:53:26.300-0300] {standard_task_runner.py:100} ERROR - Failed to execute job 60 for task TopCTR (TopCTR() missing 1 required positional argument: 'ads_views'; 2027)
[2023-05-07T15:53:26.327-0300] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-07T15:53:26.347-0300] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
