[2023-05-02T22:11:38.434-0300] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bigdata_tp.FiltrarDatos manual__2023-05-03T01:11:32.981547+00:00 [queued]>
[2023-05-02T22:11:38.448-0300] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bigdata_tp.FiltrarDatos manual__2023-05-03T01:11:32.981547+00:00 [queued]>
[2023-05-02T22:11:38.448-0300] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-02T22:11:38.448-0300] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-02T22:11:38.449-0300] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-02T22:11:38.470-0300] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): FiltrarDatos> on 2023-05-03 01:11:32.981547+00:00
[2023-05-02T22:11:38.497-0300] {standard_task_runner.py:55} INFO - Started process 1221 to run task
[2023-05-02T22:11:38.512-0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'bigdata_tp', 'FiltrarDatos', 'manual__2023-05-03T01:11:32.981547+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpwpnmwzzw']
[2023-05-02T22:11:38.516-0300] {standard_task_runner.py:83} INFO - Job 21: Subtask FiltrarDatos
[2023-05-02T22:11:38.609-0300] {task_command.py:389} INFO - Running <TaskInstance: bigdata_tp.FiltrarDatos manual__2023-05-03T01:11:32.981547+00:00 [running]> on host DESKTOP-02TA80M.localdomain
[2023-05-02T22:11:38.699-0300] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=bigdata_tp
AIRFLOW_CTX_TASK_ID=FiltrarDatos
AIRFLOW_CTX_EXECUTION_DATE=2023-05-03T01:11:32.981547+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-03T01:11:32.981547+00:00
[2023-05-02T22:11:38.701-0300] {dag.py:21} INFO - Levantando ids activos...
[2023-05-02T22:11:38.715-0300] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alanmatys/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/alanmatys/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/alanmatys/airflow/dags/dag.py", line 25, in FiltrarDatos
    ads_views = pd.read_csv('~/airflow/data/raw/adv_views.csv').isin(ads_ids['advertiser_id'])
  File "/home/alanmatys/airflow_env/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/alanmatys/airflow_env/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/alanmatys/airflow_env/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/alanmatys/airflow_env/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/alanmatys/airflow_env/lib/python3.10/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/home/alanmatys/airflow/data/raw/adv_views.csv'
[2023-05-02T22:11:38.726-0300] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=bigdata_tp, task_id=FiltrarDatos, execution_date=20230503T011132, start_date=20230503T011138, end_date=20230503T011138
[2023-05-02T22:11:38.740-0300] {standard_task_runner.py:100} ERROR - Failed to execute job 21 for task FiltrarDatos ([Errno 2] No such file or directory: '/home/alanmatys/airflow/data/raw/adv_views.csv'; 1221)
[2023-05-02T22:11:38.761-0300] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-02T22:11:38.782-0300] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
